"""empty message

Revision ID: 560e10d7d531
Revises: 
Create Date: 2019-08-11 13:19:39.628032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '560e10d7d531'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Projects',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('creation_time', sa.DateTime(), nullable=False),
    sa.Column('last_edition_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_table('Users',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('username')
    )
    op.create_table('Diagrams',
    sa.Column('diagram_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('creation_time', sa.DateTime(), nullable=False),
    sa.Column('last_edition_time', sa.DateTime(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['Projects.project_id'], ),
    sa.PrimaryKeyConstraint('diagram_id')
    )
    op.create_table('ProjectPermissions',
    sa.Column('project_permission_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('Subscriber', 'Editor', 'Administrator', name='projectpermissiontypes'), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['Projects.project_id'], ),
    sa.ForeignKeyConstraint(['username'], ['Users.username'], ),
    sa.PrimaryKeyConstraint('project_permission_id')
    )
    op.create_table('TokenBlacklist',
    sa.Column('token_id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('token_type', sa.String(length=10), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('expires', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['username'], ['Users.username'], ),
    sa.PrimaryKeyConstraint('token_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('TokenBlacklist')
    op.drop_table('ProjectPermissions')
    op.drop_table('Diagrams')
    op.drop_table('Users')
    op.drop_table('Projects')
    # ### end Alembic commands ###
