"""empty message

Revision ID: 5facc45453c9
Revises: 70ce942c34e6
Create Date: 2019-08-16 20:02:16.195342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5facc45453c9'
down_revision = '70ce942c34e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('data', sa.LargeBinary(), nullable=True),
    sa.Column('expiry', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sessions')
    # ### end Alembic commands ###
