"""empty message

Revision ID: 637b34e16087
Revises: b251ff0cc893
Create Date: 2019-08-10 19:30:21.425654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '637b34e16087'
down_revision = 'b251ff0cc893'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ProjectPermissions', sa.Column('project_permission_id', sa.Integer(), nullable=False))
    op.drop_column('ProjectPermissions', 'permission_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ProjectPermissions', sa.Column('permission_id', sa.INTEGER(), server_default=sa.text('nextval(\'"ProjectPermissions_permission_id_seq"\'::regclass)'), autoincrement=True, nullable=False))
    op.drop_column('ProjectPermissions', 'project_permission_id')
    # ### end Alembic commands ###
